[tool.poetry]
package-mode = false
name = "streamlit-usermanager-demo"
version = "0.1.0"
description = ""
authors = ["Kai Poitschke <kai@poitschke.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "~1.40"
python-dotenv = "^1.0.1"
streamlit-ldap-authenticator = "^0.2.5"
streamlit-extras = "^0.5.0"
pydantic = {version = "^2.8.2", extras=["email"]}
streamlit-option-menu = "^0.4.0"
validate-email = "^1.3"
codetiming = "^1.4.0"
sendgrid = "^6.11.0"
casbin = "^1.36.0"
icecream = "^2.1.3"
sqlalchemy = "^2.0.29"
pydantic-settings = "^2.2.1"
streamlit-rsa-auth-ui = "^1.1.1"
pendulum = "^3.0.0"
pandas = "^2.2.2"
pyodbc = "^5.2.0"
sqlmodel = "^0.0.22"

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"
isort = "^5.13.2"
mypy = "^1.9.0"
pytest = "^8.1.1"
types-pyyaml = "^6.0.12.20240311"
bump-my-version = "^0.20.0"
ruff = "^0.4"
coverage = "^7.5.0"
sqlalchemy2-stubs = "^0.0.2a38"

[tool.black]
line-length = 79
#skip-string-normalization = true
target-version = ['py311', 'py312']

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
plugins = [
    "pydantic.mypy",
]

follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true
ignore_missing_imports = true

[tool.pytest.ini_options]
minversion = "8.0"
#addopts = "-ra -q -vvvv --color=yes --no-header --no-summary"
addopts = "-ra -q -vvvv --color=yes --no-header"
pythonpath = ["."]
testpaths = [
 #   "tests",
 "app/sre_participants/tests"
]
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
