name: Docker Image CI

on:
  push:
    branches:
      - "main"
      #- 'feature/**'

    paths:
      - 'app/**/*.py'
      - 'pyproject.toml'
      - '!Dockerfile'
      - '!docker-compose*.yaml'
      - '!**/*.md'
      - 'app/CHANGELOG.md'

  pull_request:
    branches:
      - 'main'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: docker compose -f docker-compose.yml --progress=plain build
