name: Build Docker Image
run-name: "build-docker-image"
on:
  push:
    branches:
      - "main"
      #- 'feature/**'

    paths:
      - 'app/**/*.py'
      - 'smoketest.py'
      - 'pyproject.toml'
      - '!Dockerfile'
      - '!docker-compose*.yaml'
      - '!**/*.md'
      - 'app/CHANGELOG.md'

  pull_request:
    branches:
      - 'main'

jobs:

  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          git config --global url."https://x-access-token:${GH_TOKEN}@github.com/niq-ccoe-infrastructure".insteadOf "https://github.com/niq-ccoe-infrastructure" 
          uv sync --all-groups

      - name: Lint
        run:  make lint

      - name: Unit Tests
        run:  make tests

  build:
    needs: lint_and_test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: docker compose -f docker-compose.yml --progress=plain build


    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Smoketest App
      run: |
        python smoketest.py
