# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Lint and Test
run-name: "lint-and-test"
on:
  push:
    branches:
      - '*'

    paths:
      - 'app/**/*.py'
      - '.github/**'
      - 'pyproject.toml'
      - '!**/*.md'
      - 'app/CHANGELOG.md'

  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  lint_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest uv
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f pyproject.toml ]; then uv sync --all-groups; fi

    - name: Lint
      run: make lint

    - name: Test with pytest
      run: make tests
